development:
  app_id: 376239952395754
  secret_key: 153ddfa387c9564370bd4f7cc2fe3140
test:
  app_id: REPLACE WITH YOUR APP ID
  secret_key: REPLACE WITH YOUR SECRET KEY
production:
  app_id: REPLACE WITH YOUR APP ID
  secret_key: REPLACE WITH YOUR SECRET KEY
